Tenerife replay
esa-prl/bundles-rover pull request #2
Opened 2021-01-06 13:39 UTC by mstoelzle

- Add tenerife replay script to replay ga_slam without visualization
- Adjust filepath in orbiter preprocessing config to docker container
- Adjust ruby scripts to work with elevationMapMean in ga_slam

2021-01-06 14:52 UTC, levingerdes requested changes
Looking good overall and good that you even updated other people's scripts accordingly. I'd just ask for these few things before merging:

- [x] remove the commented-out Vizkit code if you don't intend to use it
- [x] write down which commit of pocolog you need
- [x] open an issue about the pocolog problem

2021-01-06 14:52 UTC, levingerdes commented on scripts/replay/tenerife_log_dems.rb
> +    ####### Vizkit Display #######
Do you want to actually use this visualization? Please remove these lines if you don't.

2021-01-06 14:52 UTC, levingerdes commented on scripts/replay/tenerife_log_dems.rb
> +bag = Orocos::Log::Replay.open(
Please mention which exact commit of the pocolog tool you require for this call to work since this posed a problem for you and open an issue so we don't lose track of it.

2021-01-06 14:52 UTC, levingerdes commented on scripts/spartanvo_ga_slam_test.rb
> +    # Vizkit.display ga_slam.elevationMapMean
Thanks for also updating also the other scripts!

2021-01-06 15:08 UTC, mstoelzle commented
@levingerdes Thanks for your feedback. Where do you want me to open the issue about pocolog? In the official repository (https://github.com/rock-core/tools-pocolog)

2021-01-06 15:27 UTC, levingerdes commented
Yes, that'd be great. That way we either make the developers aware of a problem and might get help or we find out why it's no longer supported.

2021-01-09 09:54 UTC, mstoelzle commented
@levingerdes I raised a github issue in the `rock-core/tools-pocolog` repo: https://github.com/rock-core/tools-pocolog/issues/24

2021-01-11 21:42 UTC, mstoelzle commented
@levingerdes They created a pull-request to address to issue with specifying multiple logs: https://github.com/rock-core/tools-orocosrb/pull/139

2021-01-12 10:56 UTC, levingerdes commented
Perfect! And it's even merged by now.

2021-01-12 10:57 UTC, merged